# Generated by Django 5.0.2 on 2024-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasuser",
            name="profile_pic",
            field=models.ImageField(
                default="profile/user/blank_profile.png", upload_to="profile/user/"
            ),
        ),
    ]
