# Generated by Django 5.0.2 on 2024-02-10 08:34

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_atlasuser_profile_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="atlasuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MEMBER", "Member"),
                    ("APPLICANT", "Applicant"),
                ],
                default="APPLICANT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="atlasuser",
            name="telegram_handle",
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name="atlasuser",
            name="profile_pic",
            field=models.ImageField(
                default="profile/blank_profile.png",
                upload_to=authentication.models.profile_pic_path,
            ),
        ),
    ]
