# Generated by Django 5.0.2 on 2024-02-10 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_atlasuser_role_atlasuser_telegram_handle_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="atlasuser",
            old_name="profile_pic",
            new_name="profile_picture",
        ),
    ]
