name: Atlas 3.0 Backend CI

on:
  pull_request:
    branches: ["main", "epic/*"]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
        run: |
          cd ./atlas_3
          python manage.py test
